version: '3.7'
services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6380:6379
    volumes:
      - redis:/data

  api:
      build:
        dockerfile: Dockerfile
        context: .
        target: development
      volumes:
        - .:/usr/src/app
      env_file:
      - .env
      command: npm run start:dev
      ports:
        - 3000:3000

volumes:
  redis:
    driver: local